---
kind: pipeline
name: matthiasloibl.com

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: alpine
  commands:
  - apk add git
  - git submodule update --recursive themes/hello-friend

- name: build
  image: alpine
  commands:
  - apk add curl git make
  - make hugo build

# - docker:
#   image: plugins/docker
#   repo: quay.io/metalmatze/matthiasloibl.com
#   registry: quay.io/metalmatze/matthiasloibl.com
#   tags: [ '${DRONE_COMMIT:0:8}' ]
#   secrets: [ 'docker_username', 'docker_password' ]
