workspace:
  base: /go
  path: src/git.matthiasloibl.com/metalmatze/matthiasloibl.com

pipeline:
  build:
    image: kkarczmarczyk/node-yarn
    commands:
    - make deps
    - make

  docker:
    image: plugins/docker
    repo: registry.matthiasloibl.com/matthiasloibl.com
    tags: [ '${DRONE_COMMIT:0:8}' ]

  build-twitter:
    image: golang:alpine
    commands:
    - cd twitter && go build -v

  docker-twitter:
    image: plugins/docker
    repo: registry.matthiasloibl.com/twitter.matthiasloibl.com
    Dockerfile: twitter/Dockerfile
    tags: [ '${DRONE_COMMIT:0:8}' ]
