pipeline:
  build:
    image: node:alpine
    commands:
      - make deps
      - make

  docker:
    image: plugins/docker
    repo: registry.matthiasloibl.com/matthiasloibl.com
    tags: [ '${DRONE_COMMIT:0:8}' ]
