build:
  image: node:latest
  commands:
    - make deps
    - make

deploy:
  rsync:
    when:
      branch: master
    user: metalmatze
    host: matthiasloibl.com
    port: 1234
    source: public/*
    target: web/matthiasloibl.com/matthiasloibl.com
    delete: true
    recursive: true
  rsync:
    when:
      branch: develop
    user: metalmatze
    host: matthiasloibl.com
    port: 1234
    source: public/*
    target: web/matthiasloibl.com/dev.matthiasloibl.com
    delete: true
    recursive: true
