---
kind: pipeline
name: matthiasloibl.com

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: alpine
  commands:
  - apk add git
  - git submodule update --init --recursive themes/hello-friend

- name: build
  image: alpine
  commands:
  - apk add curl git make
  - make hugo build

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/metalmatze/matthiasloibl.com
    tags:
      - ${DRONE_COMMIT_SHA:0:7}
  when:
    branch:
    - master
    event:
    - push

- name: deploy
  pull: always
  image: quay.io/signalcd/drone
  environment:
    PLUGIN_API_URL:
      from_secret: signalcd_api
    PLUGIN_BASICAUTH_USERNAME:
      from_secret: signalcd_username
    PLUGIN_BASICAUTH_PASSWORD:
      from_secret: signalcd_password
  when:
    branch:
      - master
    event:
      - push

