name: hugo-deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - uses: jakejarvis/hugo-build-action@v0.80.0
      with:
        args: --minify

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          quay.io/metalmatze/matthiasloibl.com:latest
